name: Deploy Heroku

on:
    release:
        types: [created]

jobs:
    Static-Check:
        uses: bmitchinson/notion-publish-tool/.github/workflows/static.yml@main
        secrets: inherit

    Deploy-App:
        runs-on: ubuntu-latest
        needs: [Static-Check]
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'notion-publish-tool'
                  heroku_email: 'mitchinson.dev@gmail.com'
                  usedocker: true
                  docker_build_args: |
                      HELLO_MSG
              env:
                  HELLO_MSG: ${{secrets.HELLO_MSG}}
