name: Heroku Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'notion-publish-tool'
                  heroku_email: 'mitchinson.dev@gmail.com'
                  usedocker: true
                  docker_build_args: |
                      HELLO_MSG
              env:
                  TEST_ARG: ${{secrets.HELLO_MSG}}
