name: Static Analysis
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'
            - run: npm install
            - run: npm run lint

    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'
            - run: npm install
            - run: npm run build

    Deploy:
        runs-on: ubuntu-latest
        needs: [Lint, Build]
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'notion-publish-tool'
                  heroku_email: 'mitchinson.dev@gmail.com'
                  usedocker: true
                  docker_build_args: |
                      HELLO_MSG
              env:
                  HELLO_MSG: ${{secrets.HELLO_MSG}}
