name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_call:

jobs:
    Lint:
        runs-on: buildjet-4vcpu-ubuntu-2204
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.14.0'
                  cache: 'npm'
            - run: npm ci
            - run: npm run lint

    Build:
        runs-on: buildjet-4vcpu-ubuntu-2204
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.14.0'
                  cache: 'npm'
            - run: npm ci
            - run: npm run build
